### ISSUE TITLE
Unresolved Reference error in `cloud_speech.proto` file while implementing Cloud Speech-to-Text

### ISSUE THREAD

**Issue by farhanarrafi** [googleapis/java-speech#100]
#### Environment details

1. I am working with **Cloud Speech-to-Text Getting punctuation**. While trying to integrate it to my code, I get the following error in my `cloud_speech.proto` file.

![Screenshot from 2020-02-19 14-16-01](https://user-images.githubusercontent.com/6898489/74815944-58163580-5324-11ea-9117-be04d71e82be.png)

2. OS type and version: Android Studio running on Ubuntu 18.04
3. Java version: 1.8
4. google-cloud-speech version(s): v1p1beta1

#### Steps to reproduce

  1. Add the latest common protos from https://github.com/googleapis/api-common-protos
  2. Add the latest cloud_speech proto from https://github.com/googleapis/java-speech/blob/master/proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
 3. Sync project, build the source.

#### External references such as API reference guides

- https://cloud.google.com/speech-to-text/docs/automatic-punctuation#speech_transcribe_auto_punctuation-java

#### Any additional information below

1. The issue gets resolved if I add the dependency: compile 'com.google.cloud:google-cloud-speech:1.22.3'. 
But, in our current code, we are using version1 API without using the dependency.
2. Even though, the code builds successfully, the error is still there.

**Comment by nnegrey** [comment]
Howdy, are you able to use the published version of the library on maven or do you need to build from source every time?
https://mvnrepository.com/artifact/com.google.cloud/google-cloud-speech
