### ISSUE TITLE
mvn verify fails because surefire and failsafe plugins are not specified in master pom.xml 

### ISSUE THREAD

**Issue by sid-dinesh94** [googleapis/java-speech#16]
If you are still having issues, please include as much information as possible:

#### Environment details

2. OS type and version: Ubuntu
3. Java version: Java8
4. google-cloud-speect version(s):

#### Steps to reproduce

  1. Start with a completely clean environment
  2. Run a command that builds the project without running tests: mvn install -DskipTests
  3. Pull down the dependencies: dependency:go-offline
  4. Try running the tests off line: mvn --fail-at-end -o verify

#### Stack trace
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ----------------< com.google.cloud:google-cloud-speech >----------------
[INFO] Building Google Cloud Speech 1.20.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce) @ google-cloud-speech ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.0:check (checkstyle) @ google-cloud-speech ---
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.4:prepare-agent (default) @ google-cloud-speech ---
[INFO] argLine set to -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.8.4/org.jacoco.agent-0.8.4-runtime.jar=destfile=/home/root/google-cloud-speech/target/jacoco.exec
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:add-resource (add-main-proto-resources) @ google-cloud-speech ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ google-cloud-speech ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/root/google-cloud-speech/src/main/resources
[INFO] skip non existing resourceDirectory /home/root/google-cloud-speech/src/main/proto
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ google-cloud-speech ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:add-test-resource (add-test-proto-resources) @ google-cloud-speech ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ google-cloud-speech ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/root/google-cloud-speech/src/test/resources
[INFO] skip non existing resourceDirectory /home/root/google-cloud-speech/src/test/proto
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ google-cloud-speech ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ google-cloud-speech ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.394 s
[INFO] Finished at: 2019-09-30T21:20:51Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project google-cloud-speech: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test failed: java.lang.ClassNotFoundException: org.apache.maven.surefire.junit4.JUnit4Provider -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

#### Any additional information below
This has previously been fixed on the googleapis/google-cloud-java repo: https://github.com/googleapis/google-cloud-java/issues/3819

Thanks!

**Comment by chingor13** [comment]
Hmm, the surefire/failsafe plugins are configured by a shared parent project. Let me look further into why this is failing.

**Comment by chingor13** [comment]
Fixed in #22
