### ISSUE TITLE
Async speech long running audio processing op throws a CancellationException

### ISSUE THREAD

**Issue by davidsonpaul** [googleapis/java-speech#207]
#### Environment details

- OS: macOS Catalina ver 10.15.4
- Java version: 1.8.0_152
- speech version(s): tried com.google.cloud BOM versions 4.20 and then 5.7.0 (latest)

#### Steps to reproduce

- Uploaded a FLAC encoded audio file of length ~1.5 hrs to a GCS bucket
- Ran an async long running speech to text operation against the above file
- Eventually this completes with a java.util.concurrent.CancellationException
- I've also seen reports of this happening with audio greater than 20 minutes in length, that are shorter, i.e. throws the CancellationException.  Appears to work fine with audio files 20 minutes or less. 
- This all seems well within the recommended quota limits for async ops which is ~480 minutes, so in theory the calls should succeed.

#### Code example

```java
try (SpeechClient speechClient = SpeechClient.create()) {

	final RecognitionConfig config = RecognitionConfig.newBuilder()
		.setModel(model)
		.setEncoding(RecognitionConfig.AudioEncoding.FLAC)
		.setLanguageCode(languageCode)
		.setAudioChannelCount(audioChannelCount)
		.setEnableWordTimeOffsets(true)
		.build();

	final RecognitionAudio audio = RecognitionAudio.newBuilder()
		.setUri(gcsUri)
		.build();

	// Performs speech recognition on the audio file
	final OperationFuture<LongRunningRecognizeResponse,
		LongRunningRecognizeMetadata> response = speechClient
			.longRunningRecognizeAsync(config, audio);

	// Check for done response, and wait a little if not
	while (!response.isDone()) {
		Thread.sleep(1000);
	}

	List<SpeechRecognitionResult> results = response.get(900,
		TimeUnit.SECONDS).getResultsList();
```

#### Stack trace
`error.message	Task was cancelled.`
```
java.util.concurrent.CancellationException: Task was cancelled.,
at
com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1377), 
at 
com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:551),
at 
com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:408),
at
com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:93),
at
com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:68),
at
com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:133)
```

**Comment by pmakani** [comment]
@davidsonpaul could you please try below settings ? 
```Java
SpeechSettings.Builder settings = SpeechSettings.newBuilder();
settings
       .longRunningRecognizeSettings()
       .getRetrySettings()
       .toBuilder()
       .setTotalTimeout(Duration.ofMinutes(45));

SpeechClient speechClient = SpeechClient.create(settings.build());
```

**Comment by davidsonpaul** [comment]
@pmakani thanks, I tried that but am still getting the CancellationException as before for the affected audio content :(

**Comment by meisenberg** [comment]
I saw a similar issue with CancellationExceptions after five minutes, using google-cloud-speech:1.24.0 (the latest). The following seems to be working around the issue for me, but I don't fully understand the implications:

```java
SpeechSettings.Builder speechSettingsBuilder = SpeechSettings.newBuilder();
TimedRetryAlgorithm timedRetryAlgorithm = OperationTimedPollAlgorithm.create(
		// These values are copied from com.google.cloud.speech.v1.stub.SpeechStubSettings...
		RetrySettings.newBuilder()
				.setInitialRetryDelay(Duration.ofMillis(500L))
				.setRetryDelayMultiplier(1.5)
				.setMaxRetryDelay(Duration.ofMillis(5000L))
				.setInitialRpcTimeout(Duration.ZERO) // ignored
				.setRpcTimeoutMultiplier(1.0) // ignored
				.setMaxRpcTimeout(Duration.ZERO) // ignored
				.setTotalTimeout(Duration.ofMillis(86400000L))	// ... and this is the value we are overriding
				.build());
speechSettingsBuilder.longRunningRecognizeOperationSettings()
		.setPollingAlgorithm(timedRetryAlgorithm);
SpeechSettings speechSettings = speechSettingsBuilder.build();
```

I copied the timeout value from an older version that had been working for me, google-cloud-speech:0.56.0-beta.

**Comment by pauloribeiro-hotmart** [comment]
It seems these values were changed in oct 2019

https://github.com/googleapis/java-speech/pull/26

**Comment by meisenberg** [comment]
I traced the origin of this change a bit further through the code generation process. 

The OperationTimedPollAlgorithm settings are populated in this template:
https://github.com/googleapis/gapic-generator/blob/master/src/main/resources/com/google/api/codegen/java/stub_settings.snip

In this commit, the gapic configs changed so that `total_poll_timeout_millis` was no longer provided explicitly: https://github.com/googleapis/googleapis/commit/9dc1d37b6b9e9581c8ab56c6b2d3b49ff3eeb254

As a result, it looks like the template is populated with the default value set here: https://github.com/googleapis/gapic-generator/blob/master/src/main/java/com/google/api/codegen/config/LongRunningConfig.java#L39

It's hard to guess whether this was intentional, given all of the levels of indirection at play.

**Comment by ominfowave** [comment]
@chingor13 Hi, what was the final solution for this issue? Can you please suggest what to do when the audio duration is random (user-uploaded audio files)?
