### ISSUE TITLE
Timeout/DEADLINE EXCEEDED errros while running example code

### ISSUE THREAD

**Issue by usmanQNL** [googleapis/java-speech#235]
The code does not run on local machine. It goes into waiting forever loop never to return. Also, times out as a CloudFunction. Her is the snippet from the CloudFunction log.

`{
   "insertId": "000000-1c34233a-d855-4651-a62d-786c21067bda",
   "jsonPayload": {
     "message": "Failed to find a usable hardware address from the network interfaces; using random bytes: 04:e7:b5:95:4a:ca:50:47",
     "logging.googleapis.com/sourceLocation": {
       "method": "defaultMachineId",
       "file": "io/grpc/netty/shaded/io/netty/util/internal/MacAddressUtil.java"
     }
   },
   "resource": {
     "type": "cloud_function",
     "labels": {
       "region": "us-central1",
       "function_name": "function-1",
       "project_id": "nice-theater-281908"
     }
   },
   "timestamp": "2020-07-07T10:03:59.358Z",
   "severity": "WARNING",
   "labels": {
     "execution_id": "94ardyxbxnf8"
   },
   "logName": "projects/nice-theater-281908/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
   "trace": "projects/nice-theater-281908/traces/96b401c34b382f4bfcbea6e6da8836f1",
   "receiveTimestamp": "2020-07-07T10:04:09.558062646Z"
 },
 {
   "textPayload": "Function execution took 60007 ms, finished with status: 'timeout'",
   "insertId": "000000-6ea1506f-1480-43fe-a29f-483b2f598546",
   "resource": {
     "type": "cloud_function",
     "labels": {
       "function_name": "function-1",
       "region": "us-central1",
       "project_id": "nice-theater-281908"
     }
   },
   "timestamp": "2020-07-07T10:04:32.333419702Z",
   "severity": "DEBUG",
   "labels": {
     "execution_id": "94ardyxbxnf8"
   },
   "logName": "projects/nice-theater-281908/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
   "trace": "projects/nice-theater-281908/traces/96b401c34b382f4bfcbea6e6da8836f1",
   "receiveTimestamp": "2020-07-07T10:04:32.607804002Z"
 }
]`

Also experiencing similar issue with Google Text to Speech. In particular, whenever it uses a Jetty Client to make the call, it runs into a DEADLINE EXCEEDED/TIMEOUT error on both my local machine as well as a CloudFunction.

Any advice?

**Comment by munkhuushmgl** [comment]
Could you share the example code u used for this?

**Comment by b-loved-dreamer** [comment]
Hi @usmanQNL 

Thank you for posting your concern. Can you please share the code that generated this log?

**Comment by b-loved-dreamer** [comment]
Won't fix (No repro)
