### ISSUE TITLE
Persistent IT failures preventing merging PRs

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/java-speech#254]
Persistent IT failures need to be fixed:

https://source.cloud.google.com/results/invocations/5ebef2db-b878-402f-90c9-168bd4083498/targets

Blocking #233

**Comment by athakor** [comment]
@stephaniewang526 I can't reproduced it, Looks like tests are passing correctly in my local machine. 
and one more thing #233 already unblocked.

closing this issue as it's no longer persist, feel free to reopen if this issue is still persist.
