### ISSUE TITLE
How to tell if connect to Google?

### ISSUE THREAD

**Issue by alanywlee** [googleapis/java-speech#328]
1. Specify the API at the beginning of the title. 
just exactly the same as the asynchronous speech recognition sample code as
java-speech/google-cloud-speech/src/main/java/com/google/cloud/speech/v1/SpeechClient.java
2. OS type and version: ubuntu 18.04 inside docker container (docker version  18.06.1-ce)
3. Java version: 

JDK: 1.8.181

Runtime:
Openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

4. speech version(s): v1,24,4

Step to reproduce:
  1. make my example running jar inside a ubuntu 18.04 contrainer with Openjdk 1.8.0_265 installed
  2. deploy my docker to VM, some of them could run successfully, not some exactly the same spec VM got nothing
  3. I used wireshark to inspect those VM not working and found actually no tcp packet sent to Google, but
     those VM worked successfully could sent packet. Since VM spec and docker container are exactly the same,
	 I wonder maybe SpeechClient.java got stucked somewhere but don't know how to figure it out.
  4. Are there any way to diagnosis if SpeechClient.java is connected to Google?

**Comment by b-loved-dreamer** [comment]
Hi @alanywlee, would you please explain further what your goal is. Also, please can you clarify your repro steps.

**Comment by alanywlee** [comment]
Hi @b-loved-dreamer,

I am looking for a standard way to diagnosis connection status with Google in case I got no recognition result from Google. 
In my case, no exception during recognition process seems not referring connection status with Google is good, maybe connection not be able to establish with unknown reason in wireshark point of view. And in case of docker deployment, it is very hard to make sure the internet quality of all deployed machines. If I can tell the deployed environment is not able to work properly, maybe a better solution is to report an error message and destroy itself than just return no recognition result.

Similar case I encountered before: DNS of my VM environment responded very slow ( >10 sec ) during that time, client got no recognition result if timeout is not long enough.

**Comment by b-loved-dreamer** [comment]
Hi @alanywlee, STT uses REST and gRPC to service each request, depending on the request type. The details about how the connection can be probed falls outside our domain. However, you can take a look at this [documentation](https://cloud.google.com/speech-to-text/docs/basics) to try to understand the logistics of how it operates. You might want to focus your research on gRPC.

**Comment by b-loved-dreamer** [comment]
Closing this issue. Reopen if you need more clarification.
