### ISSUE TITLE
The following artifacts could not be resolved: com.google.api.grpc:proto-google-cloud-speech-v1p1beta1:jar:0.77.11-SNAPSHOT

### ISSUE THREAD

**Issue by stefan-reich** [googleapis/java-speech#404]
1. Downloaded the repo as a zip
2. cd google-cloud-speech
3. \users\stefa\downloads\apache-maven-3.6.3\bin\mvn package

Getting:

[ERROR] Failed to execute goal on project google-cloud-speech: Could not resolve dependencies for project com.google.cloud:google-cloud-speech:jar:1.24.11-SNAPSHOT: The following artifacts could not be resolved: com.google.api.grpc:proto-google-cloud-speech-v1p1beta1:jar:0.77.11-SNAPSHOT, com.google.api.grpc:proto-google-cloud-speech-v1:jar:1.24.11-SNAPSHOT, com.google.api.grpc:grpc-google-cloud-speech-v1p1beta1:jar:0.77.11-SNAPSHOT, com.google.api.grpc:grpc-google-cloud-speech-v1:jar:1.24.11-SNAPSHOT: Could not find artifact com.google.api.grpc:proto-google-cloud-speech-v1p1beta1:jar:0.77.11-SNAPSHOT -> [Help 1]

What's happening?

Edit: OK maybe it's normal for trunk? When I download 1.24.10, it's all fine.

**Comment by b-loved-dreamer** [comment]
Hi @stefan-reich, I believe you want to be in the ```samples``` directory. I assume you are trying to access our speech samples.

**Comment by stefan-reich** [comment]
Hmm it's fine for me as the release works fine. Just thought it might be interesting for you. I'll just close the issue. Thanks
