### ISSUE TITLE
SpeechToText: When coexistence with FirebasePerf, happened Duplicate class on build.

### ISSUE THREAD

**Issue by yashims** [googleapis/java-speech#425]
# Environment details

## OS
Android

## Java version
Java 8

## Speech version
v1.24.11

# Steps to reproduce
1. Installation Speech-to-Text with official [Quickstart: Using client libraries](https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries?hl=en#client-libraries-install-java)
1. Installation Firebase Pref with official [Add Firebase to your Android project](https://firebase.google.com/docs/android/setup)
1. run build

# Code example
See: [Sample app's branch and app level build.gradle](https://github.com/yashims/PlayGround-android/blob/speech-filure/app/build.gradle)

# Build log

% ./gradlew assemble
```logs
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.api.Advice found in modules jetified-proto-google-common-protos-2.0.1 (com.google.api.grpc:proto-google-common-protos:2.0.1) and jetified-protolite-well-known-types-17.1.1-runtime (com.google.firebase:protolite-well-known-types:17.1.1)
     Duplicate class com.google.api.Advice$1 found in modules jetified-proto-google-common-protos-2.0.1 (com.google.api.grpc:proto-google-common-protos:2.0.1) and jetified-protolite-well-known-types-17.1.1-runtime (com.google.firebase:protolite-well-known-types:17.1.1)
     Duplicate class com.google.api.Advice$Builder found in modules jetified-proto-google-common-protos-2.0.1 (com.google.api.grpc:proto-google-common-protos:2.0.1) and jetified-protolite-well-known-types-17.1.1-runtime (com.google.firebase:protolite-well-known-types:17.1.1)
     Duplicate class com.google.api.AdviceOrBuilder found in modules jetified-proto-google-common-protos-2.0.1 (com.google.api.grpc:proto-google-common-protos:2.0.1) and jetified-protolite-well-known-types-17.1.1-runtime (com.google.firebase:protolite-well-known-types:17.1.1)
:
:
```

#### External references such as API reference guides
- https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries
- https://firebase.google.com/docs/android/setup

Thanks!

**Comment by b-loved-dreamer** [comment]
Hi @yashims, please use the built-in [recognition activity](https://developer.android.com/reference/android/speech/RecognizerIntent), if possible. Otherwise, this [tutorial](https://cloud.google.com/community/tutorials/cloud-functions-callable) is a great explainer on calling Google Cloud APIs from your mobile app.

**Comment by yashims** [comment]
Hi @b-loved-dreamer, Thank you for response and useful information.

I tried RecognizerIntent according to your advice, and it will maybe work so well in my case!!

This issue to closed. 
Thank you for politely answering to misguided question.
