### ISSUE TITLE
InfiniteStreamRecognize sample improvment

### ISSUE THREAD

**Issue by latra** [googleapis/java-speech#734]
The sample about the usage of `StreamingRecognizeRequest` defined on `InfiniteStreamRecognize.java`, refers to the private element `langCode` from`InfiniteStreamRecognizeOptions`. Should be better to make a getter from the attribute and call the getter instead.

**Comment by kweinmeister** [comment]
As the PR was closed, we are going to close this issue for now. Please feel free to reopen if you're ready to submit the PR again.
